# Generated by Django 4.2.1 on 2023-11-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='cuisine',
            new_name='category',
        ),
    ]
